import type { Contact, Quote, Invoice, Email, Task, CalendarEvent, DashboardStats, Automation } from "./types";

export const mockContacts: Contact[] = [
  {
    id: "c1",
    name: "Marc Dupont",
    company: "Dupont Bâtiment SA",
    email: "marc.dupont@dupont-batiment.ch",
    phone: "+41 79 123 45 67",
    address: "Rue de Rive 12, 1204 Genève",
    tags: ["client", "toiture", "prioritaire"],
    notes: "Client depuis 2022. Très satisfait de nos services. A recommandé 3 nouveaux clients.",
    status: "gagné",
    score: 92,
    revenue: 48500,
    createdAt: "2024-01-15",
    updatedAt: "2024-03-10",
  },
  {
    id: "c2",
    name: "Sophie Martin",
    company: "Martin Design Studio",
    email: "sophie@martindesign.ch",
    phone: "+41 78 234 56 78",
    address: "Avenue de la Gare 8, 1003 Lausanne",
    tags: ["prospect", "design", "web"],
    notes: "Intéressée par une refonte complète de son site web + gestion réseaux sociaux.",
    status: "négociation",
    score: 78,
    revenue: 0,
    createdAt: "2024-02-20",
    updatedAt: "2024-03-12",
  },
  {
    id: "c3",
    name: "Pierre Renaud",
    company: "Renaud Immobilier",
    email: "p.renaud@renaud-immo.ch",
    phone: "+41 79 345 67 89",
    address: "Boulevard des Alpes 25, 1700 Fribourg",
    tags: ["client", "immobilier", "récurrent"],
    notes: "Gestion de 12 propriétés. Facturation mensuelle automatique.",
    status: "gagné",
    score: 95,
    revenue: 156000,
    createdAt: "2023-06-01",
    updatedAt: "2024-03-14",
  },
  {
    id: "c4",
    name: "Isabelle Chevalier",
    company: "Pharma Solutions Sàrl",
    email: "i.chevalier@pharmasolutions.ch",
    phone: "+41 78 456 78 90",
    address: "Route de Meyrin 34, 1217 Meyrin",
    tags: ["prospect", "pharma", "urgent"],
    notes: "A contacté pour un audit de processus. RDV planifié le 25 mars.",
    status: "contacté",
    score: 65,
    revenue: 0,
    createdAt: "2024-03-05",
    updatedAt: "2024-03-13",
  },
  {
    id: "c5",
    name: "Thomas Müller",
    company: "Müller Tech AG",
    email: "thomas@mullertech.ch",
    phone: "+41 79 567 89 01",
    address: "Bahnhofstrasse 45, 8001 Zürich",
    tags: ["client", "tech", "entreprise"],
    notes: "Contrat annuel. Renouvellement en juin 2024.",
    status: "gagné",
    score: 88,
    revenue: 89000,
    createdAt: "2023-03-15",
    updatedAt: "2024-02-28",
  },
  {
    id: "c6",
    name: "Céline Favre",
    company: "Atelier Favre",
    email: "celine@atelierfavre.ch",
    phone: "+41 78 678 90 12",
    address: "Rue du Marché 7, 2000 Neuchâtel",
    tags: ["prospect", "artisanat"],
    notes: "Petite entreprise artisanale. Budget limité mais potentiel à long terme.",
    status: "devis envoyé",
    score: 45,
    revenue: 0,
    createdAt: "2024-03-01",
    updatedAt: "2024-03-10",
  },
  {
    id: "c7",
    name: "Antoine Leroy",
    company: "Leroy Consulting",
    email: "a.leroy@leroyconsulting.ch",
    phone: "+41 79 789 01 23",
    address: "Quai du Seujet 18, 1201 Genève",
    tags: ["client", "consulting", "enterprise"],
    notes: "Client premium. Très exigeant mais paie rapidement.",
    status: "gagné",
    score: 91,
    revenue: 234000,
    createdAt: "2022-11-01",
    updatedAt: "2024-03-15",
  },
  {
    id: "c8",
    name: "Laura Brunner",
    company: "Brunner Events",
    email: "laura@brunnerevents.ch",
    phone: "+41 78 890 12 34",
    address: "Hauptgasse 12, 4500 Soleure",
    tags: ["prospect", "events", "saisonnier"],
    notes: "Organise des événements d'entreprise. Saisonnier (pic mars-juin et sept-nov).",
    status: "prospect",
    score: 35,
    revenue: 0,
    createdAt: "2024-03-10",
    updatedAt: "2024-03-10",
  },
];

export const mockQuotes: Quote[] = [
  {
    id: "q1",
    number: "DEV-2024-001",
    contactId: "c6",
    contactName: "Céline Favre",
    company: "Atelier Favre",
    status: "envoyé",
    items: [
      { id: "qi1", description: "Site web vitrine – design et développement", quantity: 1, unitPrice: 3200, total: 3200 },
      { id: "qi2", description: "Hébergement annuel + domaine", quantity: 1, unitPrice: 240, total: 240 },
      { id: "qi3", description: "Formation CMS (2h)", quantity: 1, unitPrice: 280, total: 280 },
    ],
    subtotal: 3720,
    taxRate: 8.1,
    tax: 301.32,
    total: 4021.32,
    validUntil: "2024-04-10",
    createdAt: "2024-03-10",
    sentAt: "2024-03-11",
    notes: "Délai de réalisation : 6 semaines après validation du devis.",
  },
  {
    id: "q2",
    number: "DEV-2024-002",
    contactId: "c2",
    contactName: "Sophie Martin",
    company: "Martin Design Studio",
    status: "consulté",
    items: [
      { id: "qi4", description: "Refonte site web – UX/UI + développement", quantity: 1, unitPrice: 8500, total: 8500 },
      { id: "qi5", description: "Gestion réseaux sociaux (6 mois)", quantity: 6, unitPrice: 800, total: 4800 },
      { id: "qi6", description: "Stratégie contenu + rédaction (6 mois)", quantity: 6, unitPrice: 500, total: 3000 },
    ],
    subtotal: 16300,
    taxRate: 8.1,
    tax: 1320.3,
    total: 17620.3,
    validUntil: "2024-04-20",
    createdAt: "2024-03-12",
    sentAt: "2024-03-13",
    viewedAt: "2024-03-14",
  },
  {
    id: "q3",
    number: "DEV-2024-003",
    contactId: "c5",
    contactName: "Thomas Müller",
    company: "Müller Tech AG",
    status: "accepté",
    items: [
      { id: "qi7", description: "Audit de sécurité informatique", quantity: 1, unitPrice: 4500, total: 4500 },
      { id: "qi8", description: "Plan de remédiation + rapport", quantity: 1, unitPrice: 2000, total: 2000 },
      { id: "qi9", description: "Mise en conformité ISO 27001", quantity: 1, unitPrice: 8000, total: 8000 },
    ],
    subtotal: 14500,
    taxRate: 8.1,
    tax: 1174.5,
    total: 15674.5,
    validUntil: "2024-04-15",
    createdAt: "2024-03-08",
    sentAt: "2024-03-09",
    viewedAt: "2024-03-10",
    acceptedAt: "2024-03-15",
  },
  {
    id: "q4",
    number: "DEV-2024-004",
    contactId: "c4",
    contactName: "Isabelle Chevalier",
    company: "Pharma Solutions Sàrl",
    status: "brouillon",
    items: [
      { id: "qi10", description: "Audit des processus métier", quantity: 1, unitPrice: 5500, total: 5500 },
      { id: "qi11", description: "Rapport de recommandations", quantity: 1, unitPrice: 1500, total: 1500 },
    ],
    subtotal: 7000,
    taxRate: 8.1,
    tax: 567,
    total: 7567,
    validUntil: "2024-04-30",
    createdAt: "2024-03-14",
  },
  {
    id: "q5",
    number: "DEV-2024-005",
    contactId: "c7",
    contactName: "Antoine Leroy",
    company: "Leroy Consulting",
    status: "accepté",
    items: [
      { id: "qi12", description: "Conseil en stratégie d'entreprise (Q2 2024)", quantity: 1, unitPrice: 18000, total: 18000 },
      { id: "qi13", description: "Ateliers de direction (4 × 1 jour)", quantity: 4, unitPrice: 4500, total: 18000 },
    ],
    subtotal: 36000,
    taxRate: 8.1,
    tax: 2916,
    total: 38916,
    validUntil: "2024-04-01",
    createdAt: "2024-03-01",
    sentAt: "2024-03-02",
    viewedAt: "2024-03-03",
    acceptedAt: "2024-03-05",
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "i1",
    number: "FAC-2024-001",
    contactId: "c3",
    contactName: "Pierre Renaud",
    company: "Renaud Immobilier",
    status: "payée",
    items: [
      { id: "ii1", description: "Gestion locative – Février 2024 (12 biens)", quantity: 12, unitPrice: 150, total: 1800 },
      { id: "ii2", description: "États des lieux (3 unités)", quantity: 3, unitPrice: 200, total: 600 },
    ],
    subtotal: 2400,
    taxRate: 8.1,
    tax: 194.4,
    total: 2594.4,
    dueDate: "2024-03-15",
    createdAt: "2024-03-01",
    paidAt: "2024-03-10",
  },
  {
    id: "i2",
    number: "FAC-2024-002",
    contactId: "c7",
    contactName: "Antoine Leroy",
    company: "Leroy Consulting",
    status: "payée",
    items: [
      { id: "ii3", description: "Conseil stratégique – Q1 2024", quantity: 1, unitPrice: 18000, total: 18000 },
      { id: "ii4", description: "Ateliers de direction (2 × 1 jour)", quantity: 2, unitPrice: 4500, total: 9000 },
    ],
    subtotal: 27000,
    taxRate: 8.1,
    tax: 2187,
    total: 29187,
    dueDate: "2024-02-29",
    createdAt: "2024-02-01",
    paidAt: "2024-02-25",
    quoteId: "q5",
  },
  {
    id: "i3",
    number: "FAC-2024-003",
    contactId: "c5",
    contactName: "Thomas Müller",
    company: "Müller Tech AG",
    status: "envoyé",
    items: [
      { id: "ii5", description: "Audit de sécurité informatique", quantity: 1, unitPrice: 4500, total: 4500 },
      { id: "ii6", description: "Plan de remédiation + rapport", quantity: 1, unitPrice: 2000, total: 2000 },
    ],
    subtotal: 6500,
    taxRate: 8.1,
    tax: 526.5,
    total: 7026.5,
    dueDate: "2024-04-15",
    createdAt: "2024-03-15",
    quoteId: "q3",
  },
  {
    id: "i4",
    number: "FAC-2024-004",
    contactId: "c1",
    contactName: "Marc Dupont",
    company: "Dupont Bâtiment SA",
    status: "en_retard",
    items: [
      { id: "ii7", description: "Étude technique toiture (phase 1)", quantity: 1, unitPrice: 3500, total: 3500 },
      { id: "ii8", description: "Déplacement et rapport", quantity: 1, unitPrice: 500, total: 500 },
    ],
    subtotal: 4000,
    taxRate: 8.1,
    tax: 324,
    total: 4324,
    dueDate: "2024-03-01",
    createdAt: "2024-02-01",
    notes: "2ème relance envoyée le 10 mars.",
  },
  {
    id: "i5",
    number: "FAC-2024-005",
    contactId: "c3",
    contactName: "Pierre Renaud",
    company: "Renaud Immobilier",
    status: "envoyé",
    items: [
      { id: "ii9", description: "Gestion locative – Mars 2024 (12 biens)", quantity: 12, unitPrice: 150, total: 1800 },
      { id: "ii10", description: "Recherche locataires (2 biens)", quantity: 2, unitPrice: 800, total: 1600 },
    ],
    subtotal: 3400,
    taxRate: 8.1,
    tax: 275.4,
    total: 3675.4,
    dueDate: "2024-04-15",
    createdAt: "2024-03-15",
  },
  {
    id: "i6",
    number: "FAC-2024-006",
    contactId: "c7",
    contactName: "Antoine Leroy",
    company: "Leroy Consulting",
    status: "en attente",
    items: [
      { id: "ii11", description: "Conseil stratégique Q2 2024 (acompte 50%)", quantity: 1, unitPrice: 19458, total: 19458 },
    ],
    subtotal: 19458,
    taxRate: 0,
    tax: 0,
    total: 19458,
    dueDate: "2024-04-01",
    createdAt: "2024-03-15",
    quoteId: "q5",
  },
];

export const mockEmails: Email[] = [
  {
    id: "e1",
    from: "marc.dupont@dupont-batiment.ch",
    fromName: "Marc Dupont",
    to: "vous@fluxia.ch",
    subject: "Demande de devis – Rénovation toiture 120m²",
    preview: "Bonjour, suite à notre discussion j'aimerais recevoir un devis détaillé pour la rénovation complète...",
    body: "Bonjour,\n\nSuite à notre discussion de la semaine dernière, j'aimerais recevoir un devis détaillé pour la rénovation complète de notre toiture de 120m².\n\nNous souhaitons une intervention rapide car nous avons des infiltrations d'eau.\n\nMerci de me contacter rapidement.\n\nMarc Dupont\nDupont Bâtiment SA",
    category: "prospect",
    isRead: false,
    isStarred: true,
    receivedAt: "2024-03-15T09:23:00",
    aiSummary: "Marc Dupont demande un devis urgent pour une toiture de 120m². Il signale des infiltrations d'eau nécessitant une intervention rapide.",
    aiActions: ["Créer un devis pour Marc Dupont", "Programmer un appel de rappel", "Classifier comme priorité haute"],
    aiDraft: "Bonjour Marc,\n\nJe vous remercie de votre demande. Je prends note de l'urgence de la situation avec les infiltrations d'eau.\n\nJe vous ferai parvenir un devis détaillé pour la rénovation de votre toiture de 120m² dans les 24 heures.\n\nEn attendant, n'hésitez pas à m'appeler si la situation s'aggrave.\n\nCordialement",
    threadId: "t1",
  },
  {
    id: "e2",
    from: "compta@fournisseur-materiel.ch",
    fromName: "Comptabilité Fournitures Pro",
    to: "vous@fluxia.ch",
    subject: "Facture #F2024-4521 – Matériel mars 2024",
    preview: "Veuillez trouver ci-joint la facture pour votre commande de matériel du mois de mars...",
    body: "Bonjour,\n\nVeuillez trouver ci-joint la facture #F2024-4521 pour votre commande de matériel du mois de mars 2024.\n\nMontant total : CHF 2'340.00\nEchéance : 15 avril 2024\n\nCordialement,\nService comptabilité",
    category: "facture",
    isRead: true,
    isStarred: false,
    receivedAt: "2024-03-15T08:15:00",
    aiSummary: "Facture de fournisseur de CHF 2'340 à payer avant le 15 avril 2024.",
    aiActions: ["Enregistrer la facture", "Programmer le paiement", "Archiver"],
    threadId: "t2",
  },
  {
    id: "e3",
    from: "sophie@martindesign.ch",
    fromName: "Sophie Martin",
    to: "vous@fluxia.ch",
    subject: "RE: Devis DEV-2024-002 – Questions",
    preview: "Bonjour, merci pour le devis. J'ai quelques questions sur le calendrier et les livrables...",
    body: "Bonjour,\n\nMerci pour le devis reçu. J'ai quelques questions :\n\n1. Le délai de 8 semaines pour le site est-il négociable ? Nous aimerions lancer avant le 1er mai.\n2. Peut-on diviser le paiement en 3 fois ?\n3. Y a-t-il une maintenance incluse ?\n\nDans l'attente de votre retour,\nSophie Martin",
    category: "client",
    isRead: false,
    isStarred: true,
    receivedAt: "2024-03-14T16:42:00",
    aiSummary: "Sophie Martin pose 3 questions sur le devis : délai de livraison, paiement en 3x, et maintenance. Elle souhaite un lancement avant le 1er mai.",
    aiActions: ["Répondre aux 3 questions", "Mettre à jour le devis si nécessaire", "Proposer un appel téléphonique"],
    aiDraft: "Bonjour Sophie,\n\nMerci pour vos questions, je vais y répondre point par point :\n\n1. **Délai** : Oui, nous pouvons viser une livraison pour le 25 avril avec une mise en production au 1er mai. Cela nécessitera un démarrage immédiat.\n\n2. **Paiement en 3x** : Tout à fait possible – 33% à la commande, 33% à mi-projet, 33% à la livraison.\n\n3. **Maintenance** : Je peux inclure 3 mois de maintenance gratuite puis CHF 150/mois.\n\nSouhaiteriez-vous qu'on en discute lors d'un appel cette semaine ?\n\nCordialement",
    threadId: "t3",
  },
  {
    id: "e4",
    from: "support@client-urgent.ch",
    fromName: "Jean-Paul Petit",
    to: "vous@fluxia.ch",
    subject: "URGENT – Site web hors ligne !",
    preview: "Notre site web est complètement hors ligne depuis ce matin. Nous perdons des clients...",
    body: "URGENT !\n\nNotre site web est complètement hors ligne depuis ce matin 7h. Nous perdons des clients et des commandes en ligne !\n\nMerci d'intervenir immédiatement.\n\nJean-Paul Petit\n+41 79 888 77 66",
    category: "urgent",
    isRead: false,
    isStarred: true,
    receivedAt: "2024-03-15T07:45:00",
    aiSummary: "URGENT : Le site web d'un client est hors ligne depuis ce matin. Intervention immédiate requise.",
    aiActions: ["Contacter le client immédiatement", "Diagnostiquer le problème serveur", "Créer un ticket support prioritaire"],
    threadId: "t4",
  },
  {
    id: "e5",
    from: "partnership@agence-xyz.ch",
    fromName: "Agence XYZ",
    to: "vous@fluxia.ch",
    subject: "Proposition de partenariat – Co-marketing",
    preview: "Bonjour, nous sommes une agence de communication et aimerions explorer une collaboration...",
    body: "Bonjour,\n\nNous sommes l'Agence XYZ, spécialisée en communication digitale à Genève.\n\nNous aimerions explorer une collaboration mutuellement bénéfique : co-marketing, recommandations croisées et projets communs.\n\nSeriez-vous disponible pour un café la semaine prochaine ?\n\nCordialement,\nAgence XYZ",
    category: "partenaire",
    isRead: true,
    isStarred: false,
    receivedAt: "2024-03-14T14:22:00",
    aiSummary: "Proposition de partenariat d'une agence de communication genevoise. Potentiel de recommandations croisées.",
    aiActions: ["Évaluer le partenariat", "Planifier un rendez-vous", "Archiver si non pertinent"],
    threadId: "t5",
  },
  {
    id: "e6",
    from: "info@a.leroy@leroyconsulting.ch",
    fromName: "Antoine Leroy",
    to: "vous@fluxia.ch",
    subject: "Confirmation de la facture Q2",
    preview: "Bonjour, je confirme réception de la facture d'acompte pour Q2. Paiement effectué ce jour...",
    body: "Bonjour,\n\nJe confirme réception de la facture d'acompte pour le Q2 2024.\n\nLe paiement de CHF 19'458.- a été effectué ce jour par virement bancaire.\n\nMerci et à bientôt,\nAntoine Leroy",
    category: "client",
    isRead: true,
    isStarred: false,
    receivedAt: "2024-03-15T11:00:00",
    aiSummary: "Antoine Leroy confirme le paiement de l'acompte Q2 de CHF 19'458.",
    aiActions: ["Enregistrer le paiement", "Mettre à jour la facture FAC-2024-006", "Envoyer accusé de réception"],
    threadId: "t6",
  },
];

export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Préparer le devis pour Marc Dupont (toiture 120m²)",
    description: "Calculer les coûts matériaux et main d'œuvre pour une toiture de 120m². Inclure les options imperméabilisation.",
    priority: "haute",
    status: "en_cours",
    assignee: "Vous",
    contactId: "c1",
    contactName: "Marc Dupont",
    deadline: "2024-03-16",
    createdAt: "2024-03-15",
    tags: ["devis", "urgent"],
  },
  {
    id: "t2",
    title: "Appeler Sophie Martin – questions devis DEV-2024-002",
    priority: "haute",
    status: "todo",
    assignee: "Vous",
    contactId: "c2",
    contactName: "Sophie Martin",
    deadline: "2024-03-15",
    createdAt: "2024-03-14",
    tags: ["appel", "devis"],
  },
  {
    id: "t3",
    title: "Envoyer relance facture FAC-2024-004 (Dupont – en retard)",
    description: "3ème relance. Ton ferme mais professionnel. Proposer un plan de paiement si nécessaire.",
    priority: "haute",
    status: "todo",
    contactId: "c1",
    contactName: "Marc Dupont",
    deadline: "2024-03-15",
    createdAt: "2024-03-13",
    tags: ["relance", "facture"],
  },
  {
    id: "t4",
    title: "Préparer la réunion trimestrielle – Antoine Leroy",
    description: "Préparer le bilan Q1 et les objectifs Q2. Rapport de performance.",
    priority: "moyenne",
    status: "en_cours",
    contactId: "c7",
    contactName: "Antoine Leroy",
    deadline: "2024-03-20",
    createdAt: "2024-03-10",
    tags: ["réunion", "rapport"],
  },
  {
    id: "t5",
    title: "Mise à jour contrat Thomas Müller – renouvellement juin",
    priority: "moyenne",
    status: "todo",
    contactId: "c5",
    contactName: "Thomas Müller",
    deadline: "2024-04-30",
    createdAt: "2024-03-12",
    tags: ["contrat"],
  },
  {
    id: "t6",
    title: "Proposer une démo à Isabelle Chevalier",
    priority: "moyenne",
    status: "todo",
    contactId: "c4",
    contactName: "Isabelle Chevalier",
    deadline: "2024-03-18",
    createdAt: "2024-03-13",
    tags: ["démo", "prospect"],
  },
  {
    id: "t7",
    title: "Mettre à jour les templates de devis",
    description: "Moderniser les templates Word et PDF avec le nouveau branding.",
    priority: "basse",
    status: "todo",
    deadline: "2024-03-31",
    createdAt: "2024-03-01",
    tags: ["interne", "branding"],
  },
  {
    id: "t8",
    title: "Clôturer les comptes de février",
    priority: "basse",
    status: "terminée",
    deadline: "2024-03-10",
    createdAt: "2024-03-05",
    tags: ["comptabilité"],
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "ev1",
    title: "Appel Sophie Martin – Devis",
    start: "2024-03-15T10:00:00",
    end: "2024-03-15T10:30:00",
    type: "call",
    contactId: "c2",
    contactName: "Sophie Martin",
    color: "bg-violet-500/20 text-violet-400 border-violet-500/30",
  },
  {
    id: "ev2",
    title: "RDV Isabelle Chevalier – Audit",
    start: "2024-03-25T14:00:00",
    end: "2024-03-25T16:00:00",
    type: "meeting",
    contactId: "c4",
    contactName: "Isabelle Chevalier",
    description: "Réunion de découverte pour l'audit des processus",
    color: "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
  },
  {
    id: "ev3",
    title: "Échéance facture FAC-2024-004",
    start: "2024-03-01T00:00:00",
    end: "2024-03-01T00:00:00",
    type: "deadline",
    contactId: "c1",
    contactName: "Marc Dupont",
    color: "bg-red-500/20 text-red-400 border-red-500/30",
  },
  {
    id: "ev4",
    title: "Réunion trimestrielle – Antoine Leroy",
    start: "2024-03-20T09:00:00",
    end: "2024-03-20T12:00:00",
    type: "meeting",
    contactId: "c7",
    contactName: "Antoine Leroy",
    description: "Bilan Q1 et objectifs Q2",
    color: "bg-green-500/20 text-green-400 border-green-500/30",
  },
  {
    id: "ev5",
    title: "Relance devis Céline Favre",
    start: "2024-03-18T09:00:00",
    end: "2024-03-18T09:30:00",
    type: "reminder",
    contactId: "c6",
    contactName: "Céline Favre",
    color: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
  },
];

export const mockAutomations: Automation[] = [
  {
    id: "a1",
    name: "Nouveau prospect → Fiche CRM",
    description: "Quand un email d'un inconnu est classé Prospect par l'IA, crée automatiquement une fiche CRM.",
    trigger: { type: "email_categorized", condition: "prospect" },
    actions: [
      { type: "create_contact", target: "CRM" },
      { type: "send_notification", template: "Nouveau prospect détecté" },
    ],
    isActive: true,
    runsCount: 47,
    lastRun: "2024-03-15T09:23:00",
    createdAt: "2024-01-15",
  },
  {
    id: "a2",
    name: "Devis accepté → Créer facture",
    description: "Quand un devis passe au statut Accepté, génère automatiquement la facture correspondante.",
    trigger: { type: "quote_status_changed", condition: "accepté" },
    actions: [
      { type: "create_invoice", target: "Factures" },
      { type: "send_notification", template: "Facture créée automatiquement" },
    ],
    isActive: true,
    runsCount: 23,
    lastRun: "2024-03-15T11:00:00",
    createdAt: "2024-01-15",
  },
  {
    id: "a3",
    name: "Relance automatique devis (J+7)",
    description: "Envoie une relance automatique 7 jours après l'envoi d'un devis sans réponse.",
    trigger: { type: "quote_no_response", condition: "7 jours" },
    actions: [
      { type: "send_email", template: "Relance devis J+7" },
      { type: "create_task", target: "Suivi commercial" },
    ],
    isActive: true,
    runsCount: 18,
    lastRun: "2024-03-14T10:00:00",
    createdAt: "2024-01-20",
  },
  {
    id: "a4",
    name: "Facture impayée → Relance progressive",
    description: "Relances automatiques à J+7, J+14 et J+30 pour les factures impayées.",
    trigger: { type: "invoice_overdue" },
    actions: [
      { type: "send_email", template: "Relance facture automatique" },
      { type: "update_contact_score" },
    ],
    isActive: true,
    runsCount: 31,
    lastRun: "2024-03-15T08:00:00",
    createdAt: "2024-02-01",
  },
  {
    id: "a5",
    name: "Facture payée → Notifier l'équipe",
    description: "Notifie toute l'équipe quand une facture est marquée comme payée.",
    trigger: { type: "invoice_paid" },
    actions: [
      { type: "send_notification", template: "Paiement reçu !" },
      { type: "update_dashboard" },
    ],
    isActive: true,
    runsCount: 15,
    lastRun: "2024-03-15T11:05:00",
    createdAt: "2024-02-01",
  },
  {
    id: "a6",
    name: "Rapport hebdomadaire IA",
    description: "Génère et envoie un rapport hebdomadaire de performance chaque lundi matin.",
    trigger: { type: "schedule", condition: "Lundi 08h00" },
    actions: [
      { type: "generate_report", template: "Rapport hebdomadaire" },
      { type: "send_email", target: "Équipe direction" },
    ],
    isActive: false,
    runsCount: 8,
    lastRun: "2024-03-11T08:00:00",
    createdAt: "2024-02-12",
  },
];

export const mockDashboardStats: DashboardStats = {
  monthRevenue: 47850,
  monthRevenueGrowth: 12.4,
  yearRevenue: 312400,
  unpaidInvoices: 34734.5,
  unpaidInvoicesCount: 4,
  pendingQuotes: 25208.6,
  pendingQuotesCount: 2,
  conversionRate: 68.5,
  availableCash: 89200,
  newContacts: 8,
};

export const mockRevenueData = [
  { month: "Oct", revenue: 28400, expenses: 12100, cashflow: 16300 },
  { month: "Nov", revenue: 31200, expenses: 13400, cashflow: 17800 },
  { month: "Déc", revenue: 26800, expenses: 15200, cashflow: 11600 },
  { month: "Jan", revenue: 38500, expenses: 14800, cashflow: 23700 },
  { month: "Fév", revenue: 42300, expenses: 16200, cashflow: 26100 },
  { month: "Mar", revenue: 47850, expenses: 17400, cashflow: 30450 },
];

export const mockPipelineData = [
  { stage: "Prospect", count: 12, value: 89000 },
  { stage: "Contacté", count: 8, value: 62000 },
  { stage: "Devis envoyé", count: 5, value: 45000 },
  { stage: "Négociation", count: 3, value: 38000 },
  { stage: "Gagné", count: 24, value: 312000 },
];

export const aiChatMessages = [
  {
    role: "assistant",
    content: "Bonjour ! Je suis votre assistant Fluxia. Comment puis-je vous aider aujourd'hui ?",
    timestamp: "09:00",
  },
  {
    role: "user",
    content: "Montre-moi les devis non signés",
    timestamp: "09:01",
  },
  {
    role: "assistant",
    content: "Voici vos **2 devis en attente de signature** :\n\n**DEV-2024-001** – Céline Favre (Atelier Favre)\n- Montant : CHF 4'021\n- Statut : Envoyé le 11 mars\n- Valide jusqu'au 10 avril\n\n**DEV-2024-002** – Sophie Martin (Martin Design Studio)\n- Montant : CHF 17'620\n- Statut : Consulté le 14 mars\n- Valide jusqu'au 20 avril\n\nTotal en attente : **CHF 21'641**\n\nSouhaitez-vous que j'envoie une relance pour l'un d'eux ?",
    timestamp: "09:01",
  },
];
