export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          email: string;
          company_name: string | null;
          company_logo_url: string | null;
          company_address: string | null;
          company_city: string | null;
          company_zip: string | null;
          company_country: string;
          company_phone: string | null;
          company_website: string | null;
          company_vat: string | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          subscription_plan: "free" | "solo" | "team" | "business";
          subscription_status: string;
          subscription_period_end: string | null;
          avatar_url: string | null;
          onboarding_completed: boolean;
          ai_mode: "manuel" | "semi_autonome" | "autonome";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          email: string;
          company_name?: string | null;
          company_logo_url?: string | null;
          company_address?: string | null;
          company_city?: string | null;
          company_zip?: string | null;
          company_country?: string;
          company_phone?: string | null;
          company_website?: string | null;
          company_vat?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          subscription_plan?: "free" | "solo" | "team" | "business";
          subscription_status?: string;
          subscription_period_end?: string | null;
          avatar_url?: string | null;
          onboarding_completed?: boolean;
          ai_mode?: "manuel" | "semi_autonome" | "autonome";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          email?: string;
          company_name?: string | null;
          company_logo_url?: string | null;
          company_address?: string | null;
          company_city?: string | null;
          company_zip?: string | null;
          company_country?: string;
          company_phone?: string | null;
          company_website?: string | null;
          company_vat?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          subscription_plan?: "free" | "solo" | "team" | "business";
          subscription_status?: string;
          subscription_period_end?: string | null;
          avatar_url?: string | null;
          onboarding_completed?: boolean;
          ai_mode?: "manuel" | "semi_autonome" | "autonome";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contacts: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          email: string | null;
          phone: string | null;
          company: string | null;
          position: string | null;
          address: string | null;
          city: string | null;
          zip: string | null;
          country: string;
          status: "prospect" | "contacté" | "devis envoyé" | "négociation" | "gagné" | "perdu";
          score: number;
          revenue: number;
          tags: string[];
          notes: string | null;
          last_contact_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          email?: string | null;
          phone?: string | null;
          company?: string | null;
          position?: string | null;
          address?: string | null;
          city?: string | null;
          zip?: string | null;
          country?: string;
          status?: "prospect" | "contacté" | "devis envoyé" | "négociation" | "gagné" | "perdu";
          score?: number;
          revenue?: number;
          tags?: string[];
          notes?: string | null;
          last_contact_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          email?: string | null;
          phone?: string | null;
          company?: string | null;
          position?: string | null;
          address?: string | null;
          city?: string | null;
          zip?: string | null;
          country?: string;
          status?: "prospect" | "contacté" | "devis envoyé" | "négociation" | "gagné" | "perdu";
          score?: number;
          revenue?: number;
          tags?: string[];
          notes?: string | null;
          last_contact_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      quotes: {
        Row: {
          id: string;
          user_id: string;
          contact_id: string | null;
          number: string;
          title: string | null;
          status: "brouillon" | "envoyé" | "consulté" | "accepté" | "refusé" | "expiré";
          subtotal: number;
          tax_rate: number;
          tax_amount: number;
          total: number;
          valid_until: string | null;
          notes: string | null;
          pdf_url: string | null;
          sent_at: string | null;
          viewed_at: string | null;
          accepted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          contact_id?: string | null;
          number: string;
          title?: string | null;
          status?: "brouillon" | "envoyé" | "consulté" | "accepté" | "refusé" | "expiré";
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          total?: number;
          valid_until?: string | null;
          notes?: string | null;
          pdf_url?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          accepted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          contact_id?: string | null;
          number?: string;
          title?: string | null;
          status?: "brouillon" | "envoyé" | "consulté" | "accepté" | "refusé" | "expiré";
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          total?: number;
          valid_until?: string | null;
          notes?: string | null;
          pdf_url?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          accepted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      quote_items: {
        Row: {
          id: string;
          quote_id: string;
          description: string;
          quantity: number;
          unit_price: number;
          total: number;
          sort_order: number;
        };
        Insert: {
          id?: string;
          quote_id: string;
          description: string;
          quantity: number;
          unit_price: number;
          sort_order?: number;
        };
        Update: {
          id?: string;
          quote_id?: string;
          description?: string;
          quantity?: number;
          unit_price?: number;
          total?: number;
          sort_order?: number;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          user_id: string;
          contact_id: string | null;
          quote_id: string | null;
          number: string;
          status: "brouillon" | "envoyé" | "payée" | "en attente" | "en_retard" | "annulée";
          subtotal: number;
          tax_rate: number;
          tax_amount: number;
          total: number;
          due_date: string | null;
          notes: string | null;
          payment_reference: string | null;
          pdf_url: string | null;
          sent_at: string | null;
          paid_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          contact_id?: string | null;
          quote_id?: string | null;
          number: string;
          status?: "brouillon" | "envoyé" | "payée" | "en attente" | "en_retard" | "annulée";
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          total?: number;
          due_date?: string | null;
          notes?: string | null;
          payment_reference?: string | null;
          pdf_url?: string | null;
          sent_at?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          contact_id?: string | null;
          quote_id?: string | null;
          number?: string;
          status?: "brouillon" | "envoyé" | "payée" | "en attente" | "en_retard" | "annulée";
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          total?: number;
          due_date?: string | null;
          notes?: string | null;
          payment_reference?: string | null;
          pdf_url?: string | null;
          sent_at?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      invoice_items: {
        Row: {
          id: string;
          invoice_id: string;
          description: string;
          quantity: number;
          unit_price: number;
          total: number;
          sort_order: number;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          description: string;
          quantity: number;
          unit_price: number;
          sort_order?: number;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          description?: string;
          quantity?: number;
          unit_price?: number;
          total?: number;
          sort_order?: number;
        };
        Relationships: [];
      };
      tasks: {
        Row: {
          id: string;
          user_id: string;
          contact_id: string | null;
          title: string;
          description: string | null;
          status: "todo" | "en_cours" | "terminée";
          priority: "haute" | "moyenne" | "basse";
          deadline: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          contact_id?: string | null;
          title: string;
          description?: string | null;
          status?: "todo" | "en_cours" | "terminée";
          priority?: "haute" | "moyenne" | "basse";
          deadline?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          contact_id?: string | null;
          title?: string;
          description?: string | null;
          status?: "todo" | "en_cours" | "terminée";
          priority?: "haute" | "moyenne" | "basse";
          deadline?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      calendar_events: {
        Row: {
          id: string;
          user_id: string;
          contact_id: string | null;
          title: string;
          description: string | null;
          type: "meeting" | "call" | "deadline" | "reminder";
          start_at: string;
          end_at: string;
          location: string | null;
          google_event_id: string | null;
          color: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          contact_id?: string | null;
          title: string;
          description?: string | null;
          type?: "meeting" | "call" | "deadline" | "reminder";
          start_at: string;
          end_at: string;
          location?: string | null;
          google_event_id?: string | null;
          color?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          contact_id?: string | null;
          title?: string;
          description?: string | null;
          type?: "meeting" | "call" | "deadline" | "reminder";
          start_at?: string;
          end_at?: string;
          location?: string | null;
          google_event_id?: string | null;
          color?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      automations: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          trigger_type: string;
          trigger_config: Json;
          actions: Json;
          is_active: boolean;
          runs_count: number;
          last_run_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          trigger_type: string;
          trigger_config?: Json;
          actions?: Json;
          is_active?: boolean;
          runs_count?: number;
          last_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          trigger_type?: string;
          trigger_config?: Json;
          actions?: Json;
          is_active?: boolean;
          runs_count?: number;
          last_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
};

export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Contact = Database["public"]["Tables"]["contacts"]["Row"];
export type Quote = Database["public"]["Tables"]["quotes"]["Row"];
export type QuoteItem = Database["public"]["Tables"]["quote_items"]["Row"];
export type Invoice = Database["public"]["Tables"]["invoices"]["Row"];
export type InvoiceItem = Database["public"]["Tables"]["invoice_items"]["Row"];
export type Task = Database["public"]["Tables"]["tasks"]["Row"];
export type CalendarEvent = Database["public"]["Tables"]["calendar_events"]["Row"];
export type Automation = Database["public"]["Tables"]["automations"]["Row"];
